<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" ignored="0" total="6" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="SamsClub Mobile API" duration-ms="5264" started-at="2017-02-07T23:41:56Z" finished-at="2017-02-07T23:42:02Z">
    <groups>
    </groups>
    <test name="Test Automation Suite" duration-ms="5264" started-at="2017-02-07T23:41:56Z" finished-at="2017-02-07T23:42:02Z">
      <class name="com.samsclub.qa.SearchItemTest">
        <test-method status="PASS" signature="init(java.lang.reflect.Method)[pri:0, instance:com.samsclub.qa.SearchItemTest@7dfb0c0f]" name="init" is-config="true" duration-ms="1" started-at="2017-02-07T15:42:01Z" finished-at="2017-02-07T15:42:01Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.samsclub.qa.SearchItemTest.searchByItemNumber()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method status="PASS" signature="searchByItemNumber()[pri:0, instance:com.samsclub.qa.SearchItemTest@7dfb0c0f]" name="searchByItemNumber" duration-ms="163" started-at="2017-02-07T15:42:01Z" finished-at="2017-02-07T15:42:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- searchByItemNumber -->
        <test-method status="PASS" signature="searchByName()[pri:0, instance:com.samsclub.qa.SearchItemTest@7dfb0c0f]" name="searchByName" duration-ms="108" started-at="2017-02-07T15:42:01Z" finished-at="2017-02-07T15:42:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- searchByName -->
        <test-method status="PASS" signature="init(java.lang.reflect.Method)[pri:0, instance:com.samsclub.qa.SearchItemTest@7dfb0c0f]" name="init" is-config="true" duration-ms="0" started-at="2017-02-07T15:42:01Z" finished-at="2017-02-07T15:42:01Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.samsclub.qa.SearchItemTest.searchByName()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
      </class> <!-- com.samsclub.qa.SearchItemTest -->
      <class name="com.samsclub.qa.LoginTest">
        <test-method status="PASS" signature="init(java.lang.reflect.Method)[pri:0, instance:com.samsclub.qa.LoginTest@7d3e8655]" name="init" is-config="true" duration-ms="1182" started-at="2017-02-07T15:41:56Z" finished-at="2017-02-07T15:41:57Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.samsclub.qa.LoginTest.loginWithInvalidEmail()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method status="SKIP" signature="loginWithInvalidEmail()[pri:0, instance:com.samsclub.qa.LoginTest@7d3e8655]" name="loginWithInvalidEmail" duration-ms="1121" started-at="2017-02-07T15:41:57Z" finished-at="2017-02-07T15:41:59Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [1] but found [2]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [1] but found [2]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:179)
	at com.samsclub.qa.LoginTest.loginWithInvalidEmail(LoginTest.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginWithInvalidEmail -->
        <test-method status="PASS" signature="init(java.lang.reflect.Method)[pri:0, instance:com.samsclub.qa.LoginTest@7d3e8655]" name="init" is-config="true" duration-ms="0" started-at="2017-02-07T15:41:59Z" finished-at="2017-02-07T15:41:59Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.samsclub.qa.LoginTest.loginWithInvalidEmail()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method status="FAIL" signature="loginWithInvalidEmail()[pri:0, instance:com.samsclub.qa.LoginTest@7d3e8655]" name="loginWithInvalidEmail" duration-ms="242" started-at="2017-02-07T15:41:59Z" finished-at="2017-02-07T15:41:59Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [1] but found [2]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [1] but found [2]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:179)
	at com.samsclub.qa.LoginTest.loginWithInvalidEmail(LoginTest.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:998)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1200)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginWithInvalidEmail -->
        <test-method status="PASS" signature="init(java.lang.reflect.Method)[pri:0, instance:com.samsclub.qa.LoginTest@7d3e8655]" name="init" is-config="true" duration-ms="2" started-at="2017-02-07T15:41:59Z" finished-at="2017-02-07T15:41:59Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.samsclub.qa.LoginTest.loginWithInvalidPassword()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method status="PASS" signature="loginWithInvalidPassword()[pri:0, instance:com.samsclub.qa.LoginTest@7d3e8655]" name="loginWithInvalidPassword" duration-ms="302" started-at="2017-02-07T15:41:59Z" finished-at="2017-02-07T15:41:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginWithInvalidPassword -->
        <test-method status="PASS" signature="loginWithValidCredentials()[pri:0, instance:com.samsclub.qa.LoginTest@7d3e8655]" name="loginWithValidCredentials" duration-ms="2123" started-at="2017-02-07T15:41:59Z" finished-at="2017-02-07T15:42:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginWithValidCredentials -->
        <test-method status="PASS" signature="init(java.lang.reflect.Method)[pri:0, instance:com.samsclub.qa.LoginTest@7d3e8655]" name="init" is-config="true" duration-ms="0" started-at="2017-02-07T15:41:59Z" finished-at="2017-02-07T15:41:59Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.samsclub.qa.LoginTest.loginWithValidCredentials() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
      </class> <!-- com.samsclub.qa.LoginTest -->
    </test> <!-- Test Automation Suite -->
  </suite> <!-- SamsClub Mobile API -->
</testng-results>
